version: "3.7"

services:
  esustav_ngix:
    build: ./nginx
    container_name: esustav_nginx
    restart: unless-stopped
    ports:
      - 8700:80
    volumes:
      - ./backend/static:/static:ro
    depends_on:
      - esustav_fe
      - esustav_db
  esustav_api:
    build: ./backend
    container_name: esustav_api
    restart: unless-stopped
    volumes:
     - ./backend:/app/backend
    depends_on:
      - esustav_db

  esustav_fe:
    restart: unless-stopped
    container_name: esustav_fe
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app/backend"

  esustav_db:
    container_name: ${POSTGRES_DB_HOST}
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 15s
      timeout: 3s
      retries: 5
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
networks:
  default:
