{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "django_http_requests_before_middlewares_total",
     "legendFormat": "Number of request"
    },
    {
     "expr": "django_http_responses_before_middlewares_total",
     "legendFormat": "Number of responses"
    }
   ]
  },
  {
   "title": "Number of Authentification Request ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "authentication_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Broj CRUD operacija nad Aktivnostima",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "django_model_updates_total{model=\"activity\"}",
     "legendFormat": "Updates"
    },
    {
     "expr": "django_model_inserts_total{model=\"activity\"}",
     "legendFormat": "Inserts"
    },
    {
     "expr": "django_model_deletes_total{model=\"activity\"}",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Number of auth failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "authentication_requests_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broj korisnika koji su ocijenjeni u Suprachu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "number_graded_user_in_suprach_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}