# Generated by Django 4.1 on 2023-11-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudenti", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamgroups",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
