# Generated by Django 4.1 on 2024-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudenti", "0003_teamgroups_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissions",
            name="suprach_admin",
            field=models.BooleanField(default=False),
        ),
    ]
