# Generated by Django 4.1 on 2024-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudenti", "0004_userpermissions_suprach_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissions",
            name="can_vote",
            field=models.BooleanField(default=False),
        ),
    ]
