# Generated by Django 4.1 on 2023-10-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("estudenti", "0001_initial"),
        ("epartneri", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnernotes",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="estudenti.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="partnernotes",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="epartneri.partners"
            ),
        ),
        migrations.AddField(
            model_name="partnernotes",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="epartneri.projects",
            ),
        ),
    ]
