# Generated by Django 4.1 on 2023-10-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epartneri", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partners",
            name="oib",
            field=models.CharField(max_length=32),
        ),
    ]
