# Generated by Django 4.1 on 2023-11-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epartneri", "0003_alter_partners_oib"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
