# Generated by Django 4.1 on 2023-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suprach", "0002_alter_questionrolegroups_id_alter_questions_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suprach",
            name="grading_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suprach",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
