# Generated by Django 4.1 on 2024-01-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estudenti", "0003_teamgroups_short_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suprach", "0004_questionrolegroups_suprach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradings",
            name="graded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="graded_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="graded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="graded_user_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionrolegroups",
            name="graded_role_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="graded_role",
                to="estudenti.rolegroups",
            ),
        ),
        migrations.AlterField(
            model_name="questionrolegroups",
            name="grader_role_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="grader_role",
                to="estudenti.rolegroups",
            ),
        ),
        migrations.CreateModel(
            name="SpecialPersonForGreade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "suprach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="suprach.suprach",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gradings",
            name="special_graded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="suprach.specialpersonforgreade",
            ),
        ),
        migrations.AddField(
            model_name="likes",
            name="special_graded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="suprach.specialpersonforgreade",
            ),
        ),
        migrations.AddField(
            model_name="questionrolegroups",
            name="special_role_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="suprach.specialpersonforgreade",
            ),
        ),
        migrations.AddField(
            model_name="scores",
            name="special_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="suprach.specialpersonforgreade",
            ),
        ),
    ]
