# Generated by Django 4.1 on 2024-01-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suprach", "0005_alter_gradings_graded_alter_likes_graded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="special_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="suprach.specialpersonforgreade",
            ),
        ),
    ]
