# Generated by Django 4.1 on 2024-05-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suprach", "0007_alter_comments_user_alter_scores_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialpersonforgreade",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
