# Generated by Django 4.1 on 2024-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eizbori", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("for_leadership", models.BooleanField(default=False)),
                ("for_up", models.BooleanField(default=False)),
                ("for_coordinator", models.BooleanField(default=False)),
                ("for_documents", models.BooleanField(default=False)),
            ],
        ),
    ]
