# Generated by Django 4.1 on 2024-05-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estudenti", "0004_userpermissions_suprach_admin"),
        ("eizbori", "0003_electiontype"),
    ]

    operations = [
        migrations.AddField(
            model_name="electiontype",
            name="academic_year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="estudenti.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="electiontype",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="electiontype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
