# Generated by Django 4.1 on 2024-05-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estudenti", "0004_userpermissions_suprach_admin"),
        ("eizbori", "0004_electiontype_academic_year_electiontype_active_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ElectionType",
            new_name="Elections",
        ),
    ]
