# Generated by Django 4.1 on 2024-05-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eizbori", "0005_rename_electiontype_elections"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="elections",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="eizbori.elections",
            ),
        ),
    ]
