# Generated by Django 4.1 on 2024-05-20 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eizbori", "0006_candidate_elections"),
    ]

    operations = [
        migrations.RenameField(
            model_name="votes",
            old_name="kandidatura",
            new_name="candidate",
        ),
        migrations.RenameField(
            model_name="votes",
            old_name="is_voted",
            new_name="vote",
        ),
        migrations.RemoveField(
            model_name="votes",
            name="user",
        ),
        migrations.CreateModel(
            name="IsVoted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "elections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="eizbori.elections",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
