# Generated by Django 4.1 on 2024-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eizbori", "0007_rename_kandidatura_votes_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elections",
            name="vote_active",
            field=models.BooleanField(default=False),
        ),
    ]
