# Generated by Django 5.0.6 on 2024-06-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eizbori", "0008_elections_vote_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_title", models.TextField(blank=True, null=True)),
                ("document_link", models.TextField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "elections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="eizbori.elections",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentsVotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="eizbori.votingdocuments",
                    ),
                ),
            ],
        ),
    ]
